### ISSUE TITLE
Could you provide utils.py?

### ISSUE THREAD

**Issue by XYTK0x0** [jiaxiaojunQAQ/FGSM-PGI#1]
I cannot get comparable results with my own python file.
tks

**Comment by jiaxiaojunQAQ** [comment]
> I cannot get comparable results with my own python file. tks

Sorry for this mistake. I will undate as soon as possible. And you also can get from the code of our previous work (https://github.com/jiaxiaojunQAQ/FGSM-SDI)

**Comment by jiaxiaojunQAQ** [comment]
> I cannot get comparable results with my own python file. tks

Sorry for this mistake.  I will update it as soon as possible. And you also can get it from the code of our previous work (https://github.com/jiaxiaojunQAQ/FGSM-SDI).

**Comment by jiaxiaojunQAQ** [comment]
> I cannot get comparable results with my own python file. tks

Thanks for the reminder. We have uploaded them.
